ALTER TABLE sensors DROP COLUMN coordinate;
ALTER TABLE sensors DROP COLUMN node_id;
ALTER TABLE sensors DROP COLUMN gateway_id;
ALTER TABLE sensor ADD COLUMN langitude VARCHAR(100);
ALTER TABLE sensor ADD COLUMN latitude VARCHAR(100);
ALTER TABLE sensors MODIFY COLUMN image VARCHAR(200);
ALTER TABLE sensors MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;